{% set version = "4.1.1" %}

package:
  name: simpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simpy/simpy-{{ version }}.tar.gz
  sha256: 06d0750a7884b11e0e8e20ce0bc7c6d4ed5f1743d456695340d13fdff95001a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=8.0
    - setuptools >=64
  run:
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - simpy
    - simpy.resources
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov

about:
  home: https://simpy.readthedocs.io
  summary: Event discrete, process based simulation for Python.
  license: MIT
  license_file: LICENSE.rst
  dev_url: https://gitlab.com/team-simpy/simpy
  doc_url: https://simpy.readthedocs.io
  doc_source_url: https://gitlab.com/team-simpy/simpy/-/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
